### ISSUE TITLE
Better code listings

### ISSUE THREAD

**Issue by LorenzBischof** [acteru/ipa-latex-template#2]
The current listings setup generates an overfull \hbox warning. Should also cleanup the definition and config.

**Comment by LorenzBischof** [comment]
@phil-matti Do we want to use the minted package? It supports way better code highlighting than listing and doesn't require any config. But you need to enable the -shell-escape build option and install the pygmentize python package... I think it might be worth it because IPAs contain lots of code. 

edit: There is an automated way to enable -shell-escape in texstudio: 
% !TeX TXS-program:compile = txs:///pdflatex/[--shell-escape]
I can add a latexmkrc for those that are using the terminal. Ubuntu also has a python-pygments package in their repositories.

edit2: I tried setting it up and it still doesn't work. I guess it would be cool, but not worth the effort. I'll try cleaning up the listings config

**Comment by acteru** [comment]
@lbischof Yeah sounds like a plan i agree that listing is not the best solution for syntax highlighting, looks easy to install on linux but we also need to check if its easy to use for the mac and windows users. Maybe its hard to implement, but I think we should add this feature it would increase the quality of the template a lot.

**Comment by LorenzBischof** [comment]
@phil-matti It seems the version of texlive in the ubuntu repos is quite old. The newer minted package has an outputdir option so that build files are moved into a directory. There are a few options:
- I found a script: [install-tl-ubuntu](https://github.com/scottkosty/install-tl-ubuntu) that installs the latest texlive. I think this also updates the packages. 
- Get the latest minted package from github.
- Build everything in the project root. Since pygments adds two files it is becoming really messy, so I would like to avoid this.

edit: Another option would be to make a docker image that compiles the latex code. This would also work on windows/mac with docker-machine. I'm not sure if this could be setup with texstudio. It might be possible to specify the full docker command in the settings instead of the pdflatex/latexmk command.

**Comment by LorenzBischof** [comment]
Added minted in pull request #5
